services:
  postgres:
    image: postgres:latest
    container_name: eventhivez_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventhivez
    ports:
      - "5432:5432"
    volumes:
      - eventhivez_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d eventhivez"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  eventhivez_postgres_data:
